# Generated by Django 3.2.6 on 2021-08-29 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0005_alter_document_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='PDF',
            field=models.FileField(upload_to='pdf_files', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
