# Generated by Django 3.2.6 on 2021-08-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0006_alter_document_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='some-Doc', max_length=30),
            preserve_default=False,
        ),
    ]
